#define JPR_LOG_TAG "jpr.modules"

#include "jpr/module.h"

#include <chrono>

#include "jpr/log.h"
#include "jpr/status.h"

namespace jpr {

namespace {
int64_t (*gClock)() = nullptr;
}  // namespace

void setClockForTesting(int64_t (*clock)()) { gClock = clock; }

int64_t nowMs() {
    if (gClock)
        return gClock();
    using namespace std::chrono;
    return duration_cast<milliseconds>(steady_clock::now().time_since_epoch()).count();
}

ModuleManager& ModuleManager::instance() {
    static ModuleManager manager;
    return manager;
}

void ModuleManager::add(std::unique_ptr<Module> module) {
    if (!module)
        return;
    modules_.push_back(std::move(module));
}

void ModuleManager::applyConfig() {
    Config& config = Config::instance();

    // Built alongside the binding pass so the reference file can never drift
    // from the settings the code actually reads.
    json::Value reference = json::Value::makeObject();
    reference.set("_note",
                  json::Value("Generated by jpr on every load. Lists every setting this build reads, "
                              "with its type and default. Edit jpr.json, not this file."));
    json::Value modulesReference = json::Value::makeObject();

    for (auto& module : modules_) {
        const std::string id = module->id();
        SettingSet set(config.moduleNode(id), "modules." + id);

        bool wasEnabled = module->enabled();
        module->settings(set);

        for (auto const& warning : set.warnings())
            JPR_WARN("%s", warning.c_str());
        for (auto const& unknown : set.unknownKeys())
            JPR_WARN("modules.%s.%s is not a setting this build knows about", id.c_str(), unknown.c_str());

        json::Value entry = json::Value::makeObject();
        if (module->description()[0])
            entry.set("_description", json::Value(module->description()));
        for (auto const& info : set.described()) {
            json::Value described = json::Value::makeObject();
            described.set("type", json::Value(info.type));
            described.set("default", info.defaultValue);
            if (!info.doc.empty())
                described.set("doc", json::Value(info.doc));
            if (!info.choices.empty()) {
                json::Array choices;
                for (auto const& choice : info.choices)
                    choices.emplace_back(choice);
                described.set("choices", json::Value(std::move(choices)));
            }
            entry.set(info.key, std::move(described));
        }
        modulesReference.set(id, std::move(entry));

        bool changed = wasEnabled != module->enabled();
        module->onConfigured(changed);
        if (changed)
            JPR_INFO("module %s is now %s", id.c_str(), module->enabled() ? "enabled" : "disabled");
    }

    reference.set("modules", std::move(modulesReference));
    config.writeReference(reference);
}

void ModuleManager::dispatchTick(const TickContext& tick) {
    for (auto& module : modules_)
        module->onTick(tick);
}

void ModuleManager::dispatchLocalPlayerHurt(const HurtEvent& event) {
    status::countHurtEvent();
    for (auto& module : modules_) {
        if (module->enabled())
            module->onLocalPlayerHurt(event);
    }
}

bool ModuleManager::anyWantsHurtEvents() const {
    for (auto const& module : modules_) {
        if (module->enabled() && module->wantsHurtEvents())
            return true;
    }
    return false;
}

}  // namespace jpr
